print()
print("*"*42)
print("Implement a program that prompts the user ")
print("for input and then outputs that same input ")
print("in lowercase. Punctuation and whitespace ")
print("should be outputted unchanged.")
print("*"*42)
print()
name = input("Hello user, what is your name? ")
print(name).lower()
